# Generated by Django 3.2.21 on 2024-05-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0003_auto_20240527_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturequestion',
            name='question',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
