# Generated by Django 3.2.21 on 2024-05-28 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0005_auto_20240527_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessTheFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.FloatField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_site.questioncategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_site.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='picturequestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='picturequestion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='created_by',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_set',
            field=models.ManyToManyField(to='quiz_site.QuestionCategory'),
        ),
        migrations.AlterField(
            model_name='generalknowledge',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz_site.user'),
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
        migrations.DeleteModel(
            name='PictureQuestion',
        ),
        migrations.DeleteModel(
            name='TrueFalseQuestion',
        ),
    ]
