# Generated by Django 3.2.21 on 2024-05-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0006_auto_20240528_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalknowledge',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz_site.user'),
        ),
        migrations.AlterField(
            model_name='guesstheflag',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guesstheflag',
            name='difficulty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
