# Generated by Django 3.2.21 on 2024-06-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0010_auto_20240609_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
        migrations.AlterField(
            model_name='logos',
            name='company',
            field=models.CharField(default='Placeholder', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Celebrities',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
