# Generated by Django 3.2.21 on 2024-06-11 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0013_auto_20240611_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('difficulty', models.FloatField(blank=True, null=True)),
                ('actors', models.ManyToManyField(to='quiz_site.Celebrities')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_site.questioncategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_site.user')),
            ],
        ),
    ]
