# Generated by Django 3.2.21 on 2024-06-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0015_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrities',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flags',
            name='category',
        ),
        migrations.RemoveField(
            model_name='generalknowledge',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jets',
            name='category',
        ),
        migrations.RemoveField(
            model_name='location',
            name='category',
        ),
        migrations.RemoveField(
            model_name='logos',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_set',
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
    ]
