# Generated by Django 3.2.21 on 2024-06-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0016_auto_20240612_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueOrFalse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128)),
                ('answer', models.BooleanField()),
                ('difficulty', models.FloatField()),
                ('created_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz_site.user')),
            ],
        ),
    ]
