# Generated by Django 3.2.21 on 2024-06-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0017_trueorfalse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Locations',
        ),
    ]
