# Generated by Django 3.2.21 on 2024-06-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0018_rename_location_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalknowledge',
            name='choice_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalknowledge',
            name='choice_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalknowledge',
            name='choice_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalknowledge',
            name='choice_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
