# Generated by Django 3.2.21 on 2024-06-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0019_auto_20240612_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalknowledge',
            name='choice_4',
        ),
    ]
