# Generated by Django 3.2.21 on 2024-06-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0021_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
