# Generated by Django 3.2.21 on 2024-06-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0022_questions_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question',
        ),
    ]
