# Generated by Django 3.2.21 on 2024-06-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0023_remove_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='participating',
            field=models.BooleanField(default=False),
        ),
    ]
