# Generated by Django 3.2.21 on 2024-06-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0025_auto_20240619_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='quiz_site.Questions'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(default='Quiz', max_length=100),
        ),
    ]
