# Generated by Django 3.2.21 on 2024-06-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0027_quiz_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
