# Generated by Django 3.2.21 on 2024-06-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0028_alter_quiz_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=100)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='selected',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_site.rounds'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rounds',
            field=models.ManyToManyField(to='quiz_site.Rounds'),
        ),
    ]
