# Generated by Django 3.2.21 on 2024-06-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0030_auto_20240620_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='general_knowledge_questions',
            field=models.ManyToManyField(blank=True, to='quiz_site.GeneralKnowledge'),
        ),
    ]
