# Generated by Django 3.2.21 on 2024-06-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0032_auto_20240621_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_site.quiz'),
        ),
    ]
