# Generated by Django 3.2.21 on 2024-06-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0035_alter_questions_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='celebrity_questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='flag_questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='general_knowledge_questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='jet_questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='location_questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='logo_questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='movie_questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='quiz_round',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='true_or_false_questions',
        ),
        migrations.AddField(
            model_name='questions',
            name='q_capitals',
            field=models.ManyToManyField(blank=True, related_name='capital_questions', to='quiz_site.Flags'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_celebrities',
            field=models.ManyToManyField(blank=True, related_name='celebrity_questions', to='quiz_site.Celebrities'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_fight_jets',
            field=models.ManyToManyField(blank=True, related_name='fight_jet_questions', to='quiz_site.Jets'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_flags',
            field=models.ManyToManyField(blank=True, related_name='flag_questions', to='quiz_site.Flags'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_general_knowledge',
            field=models.ManyToManyField(blank=True, related_name='general_knowledge_questions', to='quiz_site.GeneralKnowledge'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_guess_the_age',
            field=models.ManyToManyField(blank=True, related_name='guess_the_age_questions', to='quiz_site.Celebrities'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_locations',
            field=models.ManyToManyField(blank=True, related_name='location_questions', to='quiz_site.Locations'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_logos',
            field=models.ManyToManyField(blank=True, related_name='logo_questions', to='quiz_site.Logos'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_movie_release_dates',
            field=models.ManyToManyField(blank=True, related_name='movie_release_date_questions', to='quiz_site.GeneralKnowledge'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_movies',
            field=models.ManyToManyField(blank=True, related_name='movie_questions', to='quiz_site.Movies'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_true_or_false',
            field=models.ManyToManyField(blank=True, related_name='true_or_false_questions', to='quiz_site.TrueOrFalse'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_who_is_the_imposter',
            field=models.ManyToManyField(blank=True, related_name='imposter_questions', to='quiz_site.Celebrities'),
        ),
        migrations.AddField(
            model_name='questions',
            name='q_who_is_the_oldest',
            field=models.ManyToManyField(blank=True, related_name='oldest_questions', to='quiz_site.Celebrities'),
        ),
    ]
