# Generated by Django 3.2.21 on 2024-06-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0036_auto_20240621_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='q_capitals',
            new_name='capitals',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_celebrities',
            new_name='celebrities',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_fight_jets',
            new_name='fight_jets',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_flags',
            new_name='flags',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_general_knowledge',
            new_name='general_knowledge',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_guess_the_age',
            new_name='guess_the_age',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_locations',
            new_name='locations',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_logos',
            new_name='logos',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_movie_release_dates',
            new_name='movie_release_dates',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_movies',
            new_name='movies',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_true_or_false',
            new_name='true_or_false',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_who_is_the_imposter',
            new_name='who_is_the_imposter',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='q_who_is_the_oldest',
            new_name='who_is_the_oldest',
        ),
    ]
