# Generated by Django 3.2.21 on 2024-11-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0037_auto_20240621_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celebrities',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='flags',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generalknowledge',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jets',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='logos',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trueorfalse',
            name='created_by',
        ),
    ]
