# Generated by Django 3.2.21 on 2024-11-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0038_auto_20241118_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='participating',
        ),
    ]
