# Generated by Django 3.2.21 on 2024-11-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0039_remove_player_participating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
