# Generated by Django 3.2.21 on 2024-11-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0040_delete_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='random_numbers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
