# Generated by Django 3.2.21 on 2024-11-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0042_auto_20241120_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='round1_set',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='round2_set',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='round3_set',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='round4_set',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='round5_set',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='round6_set',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='round7_set',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='round8_set',
        ),
    ]
