# Generated by Django 3.2.21 on 2024-11-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0043_auto_20241120_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='incorrect_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
