# Generated by Django 3.2.21 on 2024-11-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0044_player_incorrect_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_counter',
            field=models.IntegerField(default=0),
        ),
    ]
