# Generated by Django 3.2.25 on 2024-11-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0045_quiz_question_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='incorrect_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_score',
            field=models.IntegerField(default=0),
        ),
    ]
