# Generated by Django 3.2.25 on 2024-11-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0046_auto_20241121_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrities',
            name='difficulty',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AlterField(
            model_name='generalknowledge',
            name='difficulty',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AlterField(
            model_name='jets',
            name='difficulty',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='difficulty',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AlterField(
            model_name='logos',
            name='difficulty',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='difficulty',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
        migrations.AlterField(
            model_name='trueorfalse',
            name='difficulty',
            field=models.FloatField(blank=True, default=0.5, null=True),
        ),
    ]
