# Generated by Django 3.2.21 on 2024-11-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0047_auto_20241123_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
