# Generated by Django 3.2.25 on 2024-11-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0048_rounds_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_score',
            field=models.FloatField(default=0.0),
        ),
    ]
