# Generated by Django 3.2.21 on 2024-11-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0049_alter_player_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='question_answered',
            field=models.IntegerField(choices=[(0, 'Not Answered'), (1, 'Correct'), (2, 'Incorrect')], default=0),
        ),
    ]
