# Generated by Django 3.2.21 on 2024-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0051_player_page_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos'),
        ),
    ]
