# Generated by Django 3.2.21 on 2024-12-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0052_player_player_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='page_updates',
        ),
        migrations.AddField(
            model_name='player',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
