# Generated by Django 3.2.25 on 2024-12-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0056_rename_player_scores_player_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='question_answered',
            field=models.IntegerField(choices=[(0, 'Not Answered'), (1, 'Correct'), (2, 'Incorrect'), (3, 'Partial')], default=0),
        ),
    ]
