# Generated by Django 3.2.21 on 2024-12-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0057_alter_player_question_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='current_round',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_quiz_round', to='quiz_site.rounds'),
        ),
    ]
