# Generated by Django 3.2.25 on 2024-12-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0058_quiz_current_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=250)),
                ('missing_word', models.CharField(max_length=50)),
                ('answer1', models.CharField(max_length=50)),
                ('answer2', models.CharField(max_length=50)),
                ('answer3', models.CharField(max_length=50)),
                ('difficulty', models.FloatField(blank=True, default=0.5, null=True)),
            ],
        ),
    ]
