# Generated by Django 3.2.25 on 2024-12-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0059_blanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('song_title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='music_files')),
                ('difficulty', models.FloatField(blank=True, default=0.5, null=True)),
            ],
        ),
    ]
