# Generated by Django 3.2.25 on 2024-12-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0060_music'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blanks',
        ),
    ]
