# Generated by Django 3.2.25 on 2024-12-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0061_delete_blanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
