# Generated by Django 3.2.25 on 2024-12-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0062_auto_20241225_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Landmarks',
        ),
        migrations.RenameField(
            model_name='landmarks',
            old_name='location',
            new_name='landmark',
        ),
    ]
