# Generated by Django 3.2.25 on 2024-12-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0063_auto_20241225_1256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Landmarks',
            new_name='Locations',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='landmark',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='player',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.JSONField(default=dict),
        ),
    ]
