# Generated by Django 3.2.25 on 2024-12-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0064_auto_20241225_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralKnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
