# Generated by Django 3.2.25 on 2024-12-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0066_auto_20241227_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalknowledge',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_site.generalknowledgecategory'),
        ),
    ]
