# Generated by Django 3.2.25 on 2024-12-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0067_alter_generalknowledge_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
