# Generated by Django 3.2.25 on 2025-04-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0068_auto_20241229_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='join_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
