# Generated by Django 3.2.25 on 2025-04-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0070_auto_20250406_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='join_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
