# Generated by Django 6.0 on 2025-12-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0071_quiz_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this round entails', null=True),
        ),
    ]
