# Generated by Django 3.2.21 on 2025-12-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0072_rounds_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
