# Generated by Django 3.2.21 on 2025-12-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0073_auto_20251219_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='modern_music',
            field=models.BooleanField(default=False, help_text='Mark as True if this song should be excluded from users born before 1990'),
        ),
    ]
