# Generated by Django 3.2.21 on 2025-12-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0074_music_modern_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='all_time_incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='all_time_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='all_time_score',
            field=models.FloatField(default=0.0),
        ),
    ]
