# Generated by Django 3.2.21 on 2025-12-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_site', '0075_auto_20251221_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='questions_seen',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionary mapping round types to lists of question IDs this player has seen', null=True),
        ),
    ]
